### ISSUE TITLE
Error bad marshal data when running make test

### ISSUE THREAD

**Issue by ksilber1** [UMBC-CMSC447-Spring2017-Team5/college-JUMP#61]
Whole stack trace:

```
 ~/college-JUMP $ make test
env/bin/python3 setup.py test
running test
Searching for pylint-flask
Best match: pylint-flask 0.5
Processing pylint_flask-0.5-py3.5.egg

Using /home/katherine/college-JUMP/.eggs/pylint_flask-0.5-py3.5.egg
Searching for pytest-pylint
Best match: pytest-pylint 0.7.1
Processing pytest_pylint-0.7.1-py3.5.egg

Using /home/katherine/college-JUMP/.eggs/pytest_pylint-0.7.1-py3.5.egg
Searching for pytest
Best match: pytest 3.0.7
Processing pytest-3.0.7-py3.5.egg

Using /home/katherine/college-JUMP/.eggs/pytest-3.0.7-py3.5.egg
Searching for astroid>=1.0
Best match: astroid 1.5.2
Processing astroid-1.5.2-py3.5.egg

Using /home/katherine/college-JUMP/.eggs/astroid-1.5.2-py3.5.egg
Searching for pylint>=1.0
Reading https://pypi.python.org/simple/pylint/
Best match: pylint 1.7.1
Downloading https://pypi.python.org/packages/cc/8c/d1da590769213fefedea4b345e90fce80f749c61ab9f9187b3fe19397b4b/pylint-1.7.1.tar.gz#md5=e6f4c22426df7c786551bcacaaa3f217
Processing pylint-1.7.1.tar.gz
Writing /tmp/easy_install-heisvd1m/pylint-1.7.1/setup.cfg
Running pylint-1.7.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-heisvd1m/pylint-1.7.1/egg-dist-tmp-vn9w7a0i
zip_safe flag not set; analyzing archive contents...

Installed /tmp/easy_install-heisvd1m/pylint-1.7.1/.eggs/pytest_runner-2.11.1-py3.5.egg
warning: no files found matching 'README'
warning: no files found matching 'README.Python3'
warning: no files found matching '*.jpeg' under directory 'doc'
warning: no files found matching '*.html' under directory 'doc'
zip_safe flag not set; analyzing archive contents...
Traceback (most recent call last):
  File "/home/katherine/college-JUMP/env/lib/python3.5/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/katherine/college-JUMP/env/lib/python3.5/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/katherine/college-JUMP/env/lib/python3.5/site-packages/setuptools/sandbox.py", line 243, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/home/katherine/college-JUMP/env/lib/python3.5/site-packages/setuptools/sandbox.py", line 273, in run
    return func()
  File "/home/katherine/college-JUMP/env/lib/python3.5/site-packages/setuptools/sandbox.py", line 242, in runner
    _execfile(setup_script, ns)
  File "/home/katherine/college-JUMP/env/lib/python3.5/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-heisvd1m/pylint-1.7.1/setup.py", line 173, in <module>
  File "/tmp/easy_install-heisvd1m/pylint-1.7.1/setup.py", line 170, in install
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/katherine/college-JUMP/env/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 209, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/home/katherine/college-JUMP/env/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 245, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/home/katherine/college-JUMP/env/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 355, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/home/katherine/college-JUMP/env/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 392, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 61, in <module>
    'test': PyTest,
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/katherine/college-JUMP/env/lib/python3.5/site-packages/setuptools/command/test.py", line 152, in run
    self.distribution.fetch_build_eggs(self.distribution.tests_require)
  File "/home/katherine/college-JUMP/env/lib/python3.5/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
    replace_conflicting=True,
  File "/home/katherine/college-JUMP/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 826, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/home/katherine/college-JUMP/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1092, in best_match
    return self.obtain(req, installer)
  File "/home/katherine/college-JUMP/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1104, in obtain
    return installer(requirement)
  File "/home/katherine/college-JUMP/env/lib/python3.5/site-packages/setuptools/dist.py", line 380, in fetch_build_egg
    return cmd.easy_install(req)
  File "/home/katherine/college-JUMP/env/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 663, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/katherine/college-JUMP/env/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 693, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/katherine/college-JUMP/env/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 873, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/katherine/college-JUMP/env/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1101, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/katherine/college-JUMP/env/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1087, in run_setup
    run_setup(setup_script, args)
  File "/home/katherine/college-JUMP/env/lib/python3.5/site-packages/setuptools/sandbox.py", line 246, in run_setup
    raise
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/katherine/college-JUMP/env/lib/python3.5/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/katherine/college-JUMP/env/lib/python3.5/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/home/katherine/college-JUMP/env/lib/python3.5/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/home/katherine/college-JUMP/env/lib/python3.5/site-packages/pkg_resources/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/katherine/college-JUMP/env/lib/python3.5/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/katherine/college-JUMP/env/lib/python3.5/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/katherine/college-JUMP/env/lib/python3.5/site-packages/setuptools/sandbox.py", line 243, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/home/katherine/college-JUMP/env/lib/python3.5/site-packages/setuptools/sandbox.py", line 273, in run
    return func()
  File "/home/katherine/college-JUMP/env/lib/python3.5/site-packages/setuptools/sandbox.py", line 242, in runner
    _execfile(setup_script, ns)
  File "/home/katherine/college-JUMP/env/lib/python3.5/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-heisvd1m/pylint-1.7.1/setup.py", line 173, in <module>
  File "/tmp/easy_install-heisvd1m/pylint-1.7.1/setup.py", line 170, in install
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/katherine/college-JUMP/env/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 209, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/home/katherine/college-JUMP/env/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 245, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/home/katherine/college-JUMP/env/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 355, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/home/katherine/college-JUMP/env/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 392, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)
Makefile:8: recipe for target 'test' failed
make: *** [test] Error 1
```

**Comment by ksilber1** [comment]
@alexander-bauer

**Comment by alexander-bauer** [comment]
@ksilber1 Try the method from this [StackOverflow post](http://stackoverflow.com/a/30861494/1550074):

As your regular user, from your repository root (`~/college-JUMP`, I think)
```
find . -name '*.pyc' -delete
```
Then try again. If that doesn't work,
as root (`sudo` or `su`) run
```
find /usr -name '*.pyc' -delete
```

**Comment by ksilber1** [comment]
Still doesn't work

**Comment by alexander-bauer** [comment]
@ksilber1 Can you try installing `pylint` using `pip` directly, rather than having `setuptools` install it automatically?
```
env/bin/pip install pylint
```

**Comment by ksilber1** [comment]
Thanks, we both got it working now. It was a combo of the .pyc files and the pylint installation.
